# Generated by Django 5.1.1 on 2025-02-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='name',
        ),
        migrations.AddField(
            model_name='contestant',
            name='email',
            field=models.EmailField(default='try@gcb.com.gh', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
