# Generated by Django 5.1.6 on 2025-03-07 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestant',
            options={'ordering': ['-total_marks']},
        ),
    ]
